# Production Docker Compose for BanKa MVP
version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: banka-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_DATABASE: banka_db
    networks:
      - banka-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  banka-app:
    build:
      context: .
      dockerfile: production.Dockerfile
    container_name: banka-production
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - WEB3_PROVIDER_URL=https://bsc-testnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5
      - WALLET_MNEMONIC=flee cluster north scissors random attitude mutual strategy excuse debris consider uniform
      - EVENT_FACTORY_ADDRESS=0xB03c97E3357f1D4D33E421164a5205E36bACD779
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - banka-network
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mongodb_data:
    driver: local
  app_logs:
    driver: local

networks:
  banka-network:
    driver: bridge
